### PR TITLE
Support single config generators (ninja, etc)

### PR DESCRIPTION
**Pull request by jockekilby**
Introduces single-config generator support by not using explicit <Output
Directory>/Debug or <Output Directory>/Release structure in file
copying.
The Debug/Release structure is only added when a multi-config generator
such as visual studio is used.
No changes to functionality, resulting binaries or structure when
using visual studio.

### CODE REVIEW

**Comment by jockekilby** [comment]
If merged you will need to update [the PDF with build instructions](https://github.com/leadedge/Spout2/blob/master/Building%20the%20libraries.pdf) as it is no longer necessary to switch to 'Release' before building.

**Comment by leadedge** [comment]
I will have a look at this and get back to you.

**Comment by leadedge** [comment]
It all works fine here with Visual Studio 2017. I would like to get the original author to look at it with different compilers if he can. I will attempt to merge into the Beta branch and we can use that for more things you would like to add.

**Comment by leadedge** [comment]
Well that didn't go well. I ended up with lots of files to be merged. I am sure it would work out but I will copy the files across manually to be sure.

**Comment by jockekilby** [comment]
Sorry for basing on an incorrect branch, weird that you got so many conflicting files though as I only changed a single file 😄 
I'll base the next part on beta branch!

Should we close this PR then since the changes are already in beta branch?

**Comment by leadedge** [comment]
No problems. Yes let's just close this mess and continue with the beta branch.

**Pull request closed without merging**
