### PR TITLE
Fixes for clang

### PR DESCRIPTION
**Pull request by jcelerier**
Very small build fixes to allow the last version to build with clang

### CODE REVIEW

**Comment by leadedge** [comment]
I made these changes by hand and added another fix at the same time.
Please check that they are OK for you. We missed the extra __uuidof with PR#81.

**Comment by jcelerier** [comment]
thanks, I commented on the last commit ! https://github.com/leadedge/Spout2/commit/b080c3d47b72d860bb0e1b038b18acc50262c47e#diff-3de23ac31b735a8208f57407a79633202378b1511484170c752e6cd53453aefdR56

**Comment by jcelerier** [comment]
would you accept a PR that sets up continuous integration to make sure that it keeps building ?

**Comment by leadedge** [comment]
At the moment I don't want to accept any pull requests until the beta branch is updated and the master branch updated from it. The reason is that I had conflicts in a plugin and the resulting fix was worse than the cure and I ended up losing everything and had to start again. I don't want to risk that here.

**Comment by jcelerier** [comment]
okay no worries ! if you want I can write the file and attach them to an issue

**Pull request closed without merging**
